<?php
/******************************************************************************
    
    Match wikidata to g5.

    @license    GPL
    @history    2025-05-02 22:53:07+02:00, Thierry Graff : Creation
********************************************************************************/

declare(strict_types=1);

namespace wdg5\commands;

use wdg5\app\Config;
use wdg5\app\Sqlite;
use wdg5\model\wikidata\Property;
use wdg5\model\wikidata\Entity;
use tiglib\strings\slugify;

class command09 {
    
    /** Local sqlite database, specific to wd-g5 **/
    private static \PDO $sqlite_wd_g5;
    
    /**
        Main file generated by this command
        Contains matching rows that need to be checked before inclusion in g5
    **/
    private static $checkFile = 'var/tmp/check-match.csv';
    
    /** Directory containing wd records without name **/
    private static $nonameDir = 'var/tmp/nonames';
    
    private static $checkFileContents = "G5_NAME;WD_NAME;G5_BIRTH;WD_BIRTH;G5_PLACE;WD_PLACE;G5_OCCU;WD_OCCU;CHECK\n";
    
    public static function execute(): void {
        self::$sqlite_wd_g5 = Sqlite::getConnection(Config::$data['sqlite']['wd-g5']);
        $query = 'select * from wd_g5 where is_wd_stored = 1';
//        $query = 'select * from wd_g5 where is_wd_stored = 1 limit 15';
//        $query = "select * from wd_g5 where g5_slug='sommer-raymond-1906-08-31'";
        
        $n_match = $n_noname = 0;
        foreach(self::$sqlite_wd_g5->query($query, \PDO::FETCH_ASSOC) as $row){
            
            $g5_person = self::build_g5_person($row);
//echo $g5_person['slug'] . "\n";
            $data_wd = json_decode($row['wd_data'], true);
            foreach($data_wd as $id_wd => $candidate){
//echo "    $id_wd\n";
                // try to match only humans !
                if(
                    !isset($candidate[Property::INSTANCE_OF])
                    || $candidate[Property::INSTANCE_OF]['values'][0]['id'] != Entity::HUMAN
                ){
//echo "    $id_wd NOT HUMAN\n";
                    continue;
                }
                $wd_person = self::build_wd_person($candidate, $id_wd);
//if($g5_person['slug'] == 'pic-adrien-1863-10-03') {
if(false) {
    echo "\n"; print_r($wd_person); echo "\n"; exit;
}
                // if no birth date, useless to try matching
                if(!isset($wd_person['birth']['date'])){
//echo "    $id_wd NO BIRTHDATE\n";
                    continue;
                }
                
                $match = self::match($g5_person, $wd_person);
                if($match == 0){
//echo "    $id_wd NO MATCH\n";
                    continue;
                }
                $wd_name = self::computeWdName($wd_person);
                if($wd_name == ''){
                    $n_noname++;
//                    $filename = self::$nonameDir . DS . $g5_person['slug'] . '.json';
//echo "    $id_wd NO NAME\n";
//                    file_put_contents($filename, json_encode($data_wd, JSON_PRETTY_PRINT));
//exit;
                    continue;
                }
                $n_match++;
                self::$checkFileContents .=
                        self::computeG5Name($g5_person)
                . ';' . $wd_name
                . ';' . self::computeG5Birth($g5_person)
                . ';' . self::computeWdBirth($wd_person)
                . ';' . self::computeG5Place($g5_person)
                . ';' . self::computeWdPlace($wd_person)
                . ';' . self::computeG5Occu($g5_person)
                . ';' . self::computeWdOccu($wd_person)
                . ';' . ($match == 1 ? 'N' : 'Y')
                . "\n";
//echo "    $id_wd --- ok ---\n";
            }
        }
        file_put_contents(self::$checkFile, self::$checkFileContents);
        echo "Generated file " . self::$checkFile . "\n";
        echo "N match   : $n_match\n";
        echo "N no name : $n_noname\n";
    }
    
    
    // ============================= Compute fields for output file =============================
    public static function computeG5Name(&$p): string {
        return $p['name']['given'] . ' ' . $p['name']['family'];
    }
    
    public static function computeWdName(&$p): string {
        if(isset($p['name']['given'][0]) && isset($p['name']['family'][0])){
            return $p['name']['given'][0] . ' ' . $p['name']['family'][0];
        }
        if(isset($p['name']['official']['full'][0])){
            return $p['name']['official']['full'][0];
        }
        return '';
    }
    
    public static function computeG5Birth(&$p): string {
        return !is_null($p['birth']['date'])
            ? substr($p['birth']['date'], 0, 10)
            : substr($p['birth']['date-ut'], 0, 10);
    }
    
    public static function computeWdBirth(&$p): string {
        return implode('+', $p['birth']['date']);
    }
    
    public static function computeG5Place(&$p): string {
        if(isset($p['birth']['place']['name'])){
            return $p['birth']['place']['name'];
        }
        // happens for D6 records
        return '';
    }
    
    public static function computeWdPlace(&$p): string {
        if(isset($p['birth']['place'][0]['name'])){
            return $p['birth']['place'][0]['name'];
        }
        return '';
    }
    
    public static function computeG5Occu(&$p): string {
        return implode('+', $p['occus']);
    }
    
    public static function computeWdOccu(&$p): string {
        $occus = [];
        foreach($p['occus'] as $occu){
            $occus[] = slugify::compute($occu['label']);
        }
        return implode('+', $occus);
    }
    
    // ============================= Match wd and g5 persons =============================
    
    private static function match(array &$g5_person, &$wd_person): float {
        return self::match_birthdate($g5_person, $wd_person);
        // $match_names        = self::match_names($g5_person, $wd_person);
        // $match_birthplace   = self::match_birthplace($g5_person, $wd_person);
        // $match_occus        = self::match_occus($g5_person, $wd_person);
        // $match_sex          = self::match_sex($g5_person, $wd_person);
        // return $res;
    }
    
    /** @return A match score, between 0 (no match) and 1 (match certain) **/
    private static function match_birthdate(array &$g5_person, &$wd_person): float {
        $match = 0;
        // persons coming from A file have date-ut, not date
        $g5_value = !is_null($g5_person['birth']['date'])
            ? substr($g5_person['birth']['date'], 0, 10)
            : substr($g5_person['birth']['date-ut'], 0, 10);
        foreach($wd_person['birth']['date'] as $wd_value){
            if($g5_value == $wd_value){
                $match = 1;
                break;
            }
            if(levenshtein($g5_value, $wd_value) < 2){
                $match = 0.5;
            }
        }
        return $match;
    }
    
    /**
        Try to match g5 and wd names.
        The matching takes g5 informations as reference
        @return A match score, between 0 (no match) and 1 (match certain)
    **/
    private static function match_names(array &$g5_person, &$wd_person): int {
        $match = 0; // between 0 and 1
        // nb of matches (can be higher than 1)
        $match_family = 0;
        $match_given = 0;
        $match_alter = 0;
        $match_spouse = 0;
        //
        // family
        //
        $g5_families = [];
        if(isset($g5_person['name']['family'])){
            $g5_families[] = $g5_person['name']['family'];
        }
        if(isset($g5_person['name']['official']['family'])){
            $g5_families[] = $g5_person['name']['official']['family'];
        }
        if(isset($g5_person['name']['fame']['family'])){
            $g5_families[] = $g5_person['name']['fame']['family'];
        }
        $g5_families = array_unique($g5_families);
        //
        $wd_families = [];
        if(isset($wd_person['name']['family'])){
            foreach($wd_person['name']['family'] as $wd_family){
                $wd_families[] = $wd_family;
            }
        }
        $wd_families = array_unique($wd_families);
        //
        foreach($g5_families as $g5_family){
            foreach($wd_families as $wd_family){
                if(levenshtein($g5_family, $wd_family) <= 1){
                    $match_family++;
                }
            }
        }
        //
        // given
        //
        $g5_givens = [];
        if(isset($g5_person['name']['given'])){
            $g5_givens[] = $g5_person['name']['given'];
        }
        if(isset($g5_person['name']['official']['given'])){
            $g5_givens[] = $g5_person['name']['official']['given'];
        }
        if(isset($g5_person['name']['fame']['given'])){
            $g5_givens[] = $g5_person['name']['fame']['given'];
        }
        $g5_givens = array_unique($g5_givens);
        //
        $wd_givens = [];
        if(isset($wd_person['name']['given'])){
            foreach($wd_person['name']['given'] as $wd_given){
                $wd_givens[] = $wd_given;
            }
        }
        $wd_givens = array_unique($wd_givens);
        //
        foreach($g5_givens as $g5_given){
            foreach($wd_givens as $wd_given){
                if(levenshtein($g5_given, $wd_given) <= 1){
                    $match_given++;
                }
            }
        }
        //
        // alternative names - for g5, we take also ['fame']['full']
        //
        $g5_alters = [];
        if(isset($g5_person['name']['alter'])){
            foreach($g5_person['name']['alter'] as $g5_alter){
                $g5_alters[] = $g5_alter;
            }
        }
        if(isset($g5_person['name']['fame']['full'])){
            $g5_alters[] = $g5_person['name']['fame']['full'];
        }
        $g5_alters = array_unique($g5_alters);
        //
        $wd_alters = [];
        if(isset($wd_person['name']['alter'])){
            foreach($wd_person['name']['alter'] as $wd_alter){
                $wd_alters[] = $wd_alter;
            }
        }
        //
        foreach($g5_alters as $g5_alter){
            foreach($wd_alters as $wd_alter){
                if(levenshtein($g5_alter, $wd_alter) <= 1){
                    $match_alter++;
                }
            }
        }
        //
        // spouse
        //
        $g5_spouses = [];
        if(isset($g5_person['name']['spouse'])){
            $g5_spouses[] = $g5_person['name']['spouse'];
        }
        $g5_spouses = array_unique($g5_spouses);
        //
        $wd_spouses = [];
        if(isset($wd_person['name']['spouse'])){
            $wd_spouses[] = $wd_person['name']['spouse'];
        }
        //
        foreach($g5_spouses as $g5_spouse){
            foreach($wd_spouses as $wd_spouse){
                if(levenshtein($g5_spouse, $wd_spouse) <= 1){
                    $match_spouse++;
                }
            }
        }
        //
        // result
        //
        $match = ($match_family + $match_given + $match_alter + $match_spouse > 0) ? 1 : 0;
        return $match;
    }
    
    /** @return A match score, between 0 (no match) and 1 (match certain) **/
    private static function match_birthplace(array &$g5_person, &$wd_person): int {
        $match = 0;
        return $match;
    }
    
    /** @return A match score, between 0 (no match) and 1 (match certain) **/
    private static function match_occus(array &$g5_person, &$wd_person): int {
        $match = 0;
        return $match;
    }
    
    /** @return A match score, between 0 (no match) and 1 (match certain) **/
    private static function match_sex(array &$g5_person, &$wd_person): int {
        $match = 0;
        return $match;
    }
    
    private static function build_g5_person(array &$row): array {
        $res = [];
        $res['slug']    = $row['g5_slug'];
        $res['name']    = json_decode($row['g5_name'], true);
        $res['birth']   = json_decode($row['g5_birth'], true);
        $res['occus']   = json_decode($row['g5_occus'], true);
        $res['sex']     = $row['g5_sex'];
        return $res;
    }
    
    // ============================= Build wd and g5 persons =============================
    
    /** 
        Convert wd person structure to g5 person structure.
        One notable difference: each field in g5 is represented by a string,
        and corresponds to an array of values in wd.
    **/
    private static function build_wd_person(array &$candidate, $id_wd): array {
        $res = [];
        $res['id-wd'] = $id_wd;
        $res['name'] = [];
        $res['birth'] = [];
        $res['death'] = [];
        $res['occus'] = [];
        //
        // name
        //
        if(isset($candidate[Property::FAMILY_NAME])){
            $res['name']['fame']['family'] = [];
            foreach($candidate[Property::FAMILY_NAME]['values'] as $value){
                $res['name']['family'][] = $value['label'];
            }
        }
        if(isset($candidate[Property::GIVEN_NAME])){
            $res['name']['fame']['given'] = [];
            foreach($candidate[Property::GIVEN_NAME]['values'] as $value){
                $res['name']['given'][] = $value['label'];
            }
        }
        if(isset($candidate[Property::MARRIED_NAME])){
            $res['name']['spouse'] = [];
            foreach($candidate[Property::MARRIED_NAME]['values'] as $value){
                $res['name']['spouse'][] = $value['label'];
            }
        }
        // g5 field 'official' used for BIRTH_NAME, OFFICIAL_NAME, NAME_IN_NATIVE_LANGUAGE
        $res['name']['official']['full'] = [];
        if(isset($candidate[Property::BIRTH_NAME])){
            foreach($candidate[Property::BIRTH_NAME]['values'] as $value){
                $res['name']['official']['full'][] = $value['label'];
            }
        }
        if(isset($candidate[Property::NAME_IN_NATIVE_LANGUAGE])){
            foreach($candidate[Property::NAME_IN_NATIVE_LANGUAGE]['values'] as $value){
                $res['name']['official']['full'][] = $value['label'];
            }
        }
        if(isset($candidate[Property::OFFICIAL_NAME])){
            foreach($candidate[Property::OFFICIAL_NAME]['values'] as $value){
                $res['name']['official']['full'][] = $value['label'];
            }
        }
        // g5 field 'alter' used for NAME, SHORT_NAME, NICKNAME
        $res['name']['alter'] = [];
        if(isset($candidate[Property::NAME])){
            foreach($candidate[Property::NAME]['values'] as $value){
                $res['name']['alter'][] = $value['label'];
            }
        }
        if(isset($candidate[Property::SHORT_NAME])){
            foreach($candidate[Property::SHORT_NAME]['values'] as $value){
                $res['name']['alter'][] = $value['label'];
            }
        }
        if(isset($candidate[Property::NICKNAME])){
            foreach($candidate[Property::NICKNAME]['values'] as $value){
                $res['name']['alter'][] = $value['label'];
            }
        }
        //
        // Birth
        //
        if(isset($candidate[Property::DATE_OF_BIRTH])){
            $res['birth']['date'] = [];
            foreach($candidate[Property::DATE_OF_BIRTH]['values'] as $value){
                $res['birth']['date'][] = substr($value['label'], 0, 10);
            }
        }
        if(isset($candidate[Property::PLACE_OF_BIRTH])){
            $res['birth']['place'] = [];
            foreach($candidate[Property::PLACE_OF_BIRTH]['values'] as $value){
                $newPlace = [];
                $newPlace['name'] = $value['label'];
                $newPlace['wd-id'] = $value['id'];      // wd-id: field not existing in g5 model
                $res['birth']['place'][] = $newPlace;
            }
        }
        //
        // Death
        //
        if(isset($candidate[Property::DATE_OF_DEATH])){
            $res['death']['date'] = [];
            foreach($candidate[Property::DATE_OF_DEATH]['values'] as $value){
                $res['death']['date'][] = substr($value['label'], 0, 10);
            }
        }
        if(isset($candidate[Property::PLACE_OF_DEATH])){
            $res['death']['place'] = [];
            foreach($candidate[Property::PLACE_OF_DEATH]['values'] as $value){
                $newPlace = [];
                $newPlace['name'] = $value['label'];
                $newPlace['wd-id'] = $value['id'];      // wd-id: field not existing in g5 model
                $res['death']['place'][] = $newPlace;
            }
        }
        //
        // Other fields
        //
        if(isset($candidate[Property::OCCUPATION])){
            $res['occus'] = [];
            foreach($candidate[Property::OCCUPATION]['values'] as $value){
                // differs from g5, occus contains an array of slugs
                $res['occus'][] = [
                    'wd-id' => $value['id'],
                    'label' => $value['label'],
                ];
            }
        }
        if(isset($candidate[Property::SEX_OR_GENDER])){
            $res['sex'] = [];
            foreach($candidate[Property::SEX_OR_GENDER]['values'] as $value){
                $res['sex'][] = $value['id'];
            }
        }
        return $res;
    }
    
    /* 
Array
(
    [slug] => smith-adrian-1936-10-05
    [name] => Array
        (
            [fame] => Array
                (
                    [full] => 
                    [given] => 
                    [family] => 
                )

            [nobl] => 
            [alter] => Array
                (
                )

            [given] => Adrian
            [family] => Smith
            [spouse] => Array
                (
                )

            [official] => Array
                (
                    [given] => 
                    [family] => 
                )

        )

    [birth] => Array
        (
            [lmt] => 
            [tzo] => -06:00
            [date] => 1936-10-05 05:30
            [note] => 
            [place] => Array
                (
                    [c1] => 
                    [c2] => KY
                    [c3] => 
                    [cy] => US
                    [lg] => -88.53333
                    [lat] => 36.7
                    [name] => Farmington
                    [geoid] => 
                )

            [notime] => 
            [date-ut] => 1936-10-05 11:30
        )

    [occus] => Array
        (
            [0] => athletics-competitor
        )

    [sex] => M
)    */
    
} // end class
